# Generated by Django 5.2.4 on 2025-08-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmmsearchproject',
            name='tblout_file',
            field=models.FileField(blank=True, null=True, upload_to='hmmsearch/'),
        ),
    ]
