# Generated by Django 5.2.4 on 2025-08-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmsearch', '0002_hmmsearchproject_tblout_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmmsearchproject',
            name='hmm_file',
            field=models.FileField(blank=True, null=True, upload_to='hmmsearch/'),
        ),
    ]
