# Generated by Django 5.2.4 on 2025-08-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmsearch', '0003_hmmsearchproject_hmm_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmmsearchproject',
            name='domtbl_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hmmsearchproject',
            name='tblout_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
