# Generated by Django 5.2.4 on 2025-12-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmsearch', '0008_hmmsearchproject_share_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmmsearchproject',
            name='external_hmm_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hmmsearchproject',
            name='external_hmm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hmmsearchproject',
            name='hmm_source',
            field=models.CharField(blank=True, default='upload', max_length=20, null=True),
        ),
    ]
