# Generated by Django 5.2.4 on 2026-01-14 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmsearch', '0009_hmmsearchproject_external_hmm_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmmsearchproject',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hmmsearchproject',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_%(class)s_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hmmsearchproject',
            index=models.Index(fields=['user', 'task_status', '-created_at'], name='hmmsearch_h_user_id_455028_idx'),
        ),
        migrations.AddIndex(
            model_name='hmmsearchproject',
            index=models.Index(fields=['user', 'expires_at'], name='hmmsearch_h_user_id_baccc0_idx'),
        ),
        migrations.AddIndex(
            model_name='hmmsearchproject',
            index=models.Index(fields=['visibility', 'expires_at'], name='hmmsearch_h_visibil_4aaddb_idx'),
        ),
    ]
