# Generated by Django 5.2.4 on 2026-05-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmsearch', '0010_alter_hmmsearchproject_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmmsearchproject',
            name='share_inputs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hmmsearchproject',
            name='share_outputs',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hmmsearchproject',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('link', 'Link'), ('public', 'Public')], db_index=True, default='private', max_length=10),
        ),
    ]
