# Generated by Django 5.2.4 on 2026-05-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmsearch', '0012_hmmsearchproject_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmmsearchproject',
            name='hits_msa_file',
            field=models.FileField(blank=True, null=True, upload_to='hmmsearch/'),
        ),
    ]
