# Generated by Django 5.2.4 on 2026-05-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmsearch', '0013_hmmsearchproject_hits_msa_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmmsearchproject',
            name='pfamtbl_file',
            field=models.FileField(blank=True, null=True, upload_to='hmmsearch/'),
        ),
    ]
