# Generated by Django 5.2.4 on 2026-01-04 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('project_created', 'Project Created'), ('project_completed', 'Project Completed'), ('project_failed', 'Project Failed'), ('project_deleted', 'Project Deleted'), ('project_shared', 'Project Shared'), ('project_visibility_changed', 'Visibility Changed'), ('file_downloaded', 'File Downloaded')], max_length=50)),
                ('tool_type', models.CharField(choices=[('hmmbuild', 'HMMBUILD'), ('hmmemit', 'HMMEMIT'), ('hmmsearch', 'HMMSEARCH')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Action History',
                'verbose_name_plural': 'User Action Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'user'], name='users_usera_timesta_8c04a8_idx'), models.Index(fields=['user', 'tool_type'], name='users_usera_user_id_1c8e3f_idx')],
            },
        ),
    ]
