# Generated by Django 5.2.4 on 2026-04-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionhistory',
            name='action_type',
            field=models.CharField(choices=[('project_created', 'Project Created'), ('project_completed', 'Project Completed'), ('project_failed', 'Project Failed'), ('project_deleted', 'Project Deleted'), ('project_shared', 'Project Shared'), ('project_visibility_changed', 'Visibility Changed'), ('file_downloaded', 'File Downloaded'), ('workflow_run_completed', 'Pipeline Completed'), ('workflow_run_failed', 'Pipeline Failed'), ('tool_completed', 'Completed'), ('tool_failed', 'Failed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useractionhistory',
            name='tool_type',
            field=models.CharField(choices=[('hmmbuild', 'HMMBUILD'), ('hmmemit', 'HMMEMIT'), ('hmmsearch', 'HMMSEARCH'), ('workflow', 'Pipeline'), ('sequence_cleaner', 'Seq Cleaner'), ('fasta_validate', 'FASTA Validate'), ('clustalo', 'ClustalO'), ('format_convert', 'Format Convert')], max_length=20),
        ),
    ]
