# Generated by Django 5.2.4 on 2026-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_workflow_preprocessing_history_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionhistory',
            name='action_type',
            field=models.CharField(choices=[('project_created', 'Project Created'), ('project_completed', 'Project Completed'), ('project_failed', 'Project Failed'), ('project_deleted', 'Project Deleted'), ('project_shared', 'Project Shared'), ('project_visibility_changed', 'Visibility Changed'), ('file_downloaded', 'File Downloaded'), ('workflow_run_started', 'Pipeline Started'), ('workflow_run_completed', 'Pipeline Completed'), ('workflow_run_failed', 'Pipeline Failed'), ('tool_completed', 'Completed'), ('tool_failed', 'Failed')], max_length=50),
        ),
    ]
