# Generated by Django 5.2.4 on 2026-04-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
