# Generated by Django 5.2.4 on 2026-04-13 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_add_name_to_workflowrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrun',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='workflows.workflow'),
        ),
    ]
