# Generated by Django 5.2.4 on 2026-05-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_add_share_inputs_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='secondary_file',
            field=models.FileField(blank=True, help_text='Secondary input (e.g. FASTA database for hmmsearch)', null=True, upload_to='workflows/input/'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='tool_type',
            field=models.CharField(choices=[('fasta_validate', 'FASTA Validator'), ('sequence_clean', 'Sequence Cleaner'), ('clustal_omega', 'MSA (Clustal Omega)'), ('format_convert', 'Format Converter'), ('hmmbuild', 'HMM Build'), ('hmmsearch', 'HMM Search'), ('hmmemit', 'HMM Emit')], max_length=50),
        ),
    ]
