# Generated by Django 5.2.4 on 2026-05-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_steprun_step_config_snapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steprun',
            options={'ordering': ['step_order_snapshot']},
        ),
        migrations.RemoveField(
            model_name='workflowrun',
            name='secondary_file',
        ),
    ]
