# Generated by Django 5.2.4 on 2026-05-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_alter_steprun_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='tool_type',
            field=models.CharField(choices=[('fasta_validate', 'FASTA Validator'), ('sequence_clean', 'Sequence Cleaner'), ('clustal_omega', 'MSA'), ('format_convert', 'Format Converter'), ('hmmbuild', 'HMM Build'), ('hmmsearch', 'HMM Search'), ('hmmemit', 'HMM Emit')], max_length=50),
        ),
    ]
