# Generated by Django 5.2.4 on 2026-05-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_alter_workflowstep_tool_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='is_temporary',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
