# Generated by Django 5.2.4 on 2026-04-04 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClustalOmegaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('input_fasta', models.FileField(upload_to='msa_tools/clustalo/input/')),
                ('output_alignment', models.FileField(blank=True, null=True, upload_to='msa_tools/clustalo/output/')),
                ('output_format', models.CharField(choices=[('stockholm', 'Stockholm (.sto)'), ('fasta', 'Aligned FASTA (.fasta)')], default='stockholm', max_length=20)),
                ('threads', models.IntegerField(default=1)),
                ('task_status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sequence_count', models.IntegerField(blank=True, null=True)),
                ('alignment_length', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_temporary', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('share_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clustalo_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
