# Generated by Django 5.2.4 on 2026-04-04 19:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatConversionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('input_file', models.FileField(upload_to='msa_tools/converter/input/')),
                ('input_format', models.CharField(choices=[('fasta', 'Aligned FASTA'), ('clustal', 'Clustal (.aln)'), ('stockholm', 'Stockholm (.sto)')], max_length=20)),
                ('output_format', models.CharField(choices=[('fasta', 'Aligned FASTA'), ('clustal', 'Clustal (.aln)'), ('stockholm', 'Stockholm (.sto)')], max_length=20)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='msa_tools/converter/output/')),
                ('sequence_count', models.IntegerField(blank=True, null=True)),
                ('alignment_length', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_temporary', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('share_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='format_conversion_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
