# Generated by Django 5.2.4 on 2026-04-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_tools', '0002_formatconversionproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustalomegaproject',
            name='output_format',
            field=models.CharField(choices=[('stockholm', 'Stockholm (.sto)'), ('clustal', 'Clustal (.aln)'), ('fasta', 'Aligned FASTA (.fasta)')], default='stockholm', max_length=20),
        ),
    ]
