# Generated by Django 5.2.4 on 2026-05-06 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_tools', '0003_alter_clustalomegaproject_output_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clustalomegaproject',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_%(class)s_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clustalomegaproject',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('link', 'Link'), ('public', 'Public')], db_index=True, default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='formatconversionproject',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_%(class)s_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formatconversionproject',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('link', 'Link'), ('public', 'Public')], db_index=True, default='private', max_length=10),
        ),
    ]
