# Generated by Django 5.2.4 on 2026-05-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_tools', '0005_add_share_inputs_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustalomegaproject',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
