# Generated by Django 5.2.4 on 2026-05-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_tools', '0006_clustalomegaproject_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustalomegaproject',
            name='tool',
            field=models.CharField(choices=[('clustalo', 'Clustal Omega'), ('mafft', 'MAFFT'), ('muscle', 'MUSCLE'), ('kalign', 'Kalign')], default='clustalo', max_length=20),
        ),
    ]
