# Generated by Django 5.2.4 on 2026-05-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_tools', '0007_clustalomegaproject_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustalomegaproject',
            name='output_format',
            field=models.CharField(choices=[('stockholm', 'Stockholm (.sto)'), ('clustal', 'Clustal (.aln)'), ('fasta', 'Aligned FASTA (.fasta)'), ('phylip', 'Phylip (.phy)'), ('vienna', 'Vienna (.vie)')], default='stockholm', max_length=20),
        ),
    ]
