# Generated by Django 5.2.4 on 2026-05-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence_tools', '0003_fastavalidationproject_shared_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastavalidationproject',
            name='share_inputs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fastavalidationproject',
            name='share_outputs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sequencecleanerproject',
            name='share_inputs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sequencecleanerproject',
            name='share_outputs',
            field=models.BooleanField(default=True),
        ),
    ]
