# Generated by Django 5.2.4 on 2025-07-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmemit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmmemitproject',
            name='hmm_file',
            field=models.FileField(upload_to='hmmemit/'),
        ),
        migrations.AlterField(
            model_name='hmmemitproject',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='hmmemit/'),
        ),
    ]
