# Generated by Django 5.2.4 on 2025-12-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmemit', '0004_alter_hmmemitproject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmmemitproject',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='hmmemitproject',
            name='is_temporary',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
