# Generated by Django 5.2.4 on 2026-01-14 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmemit', '0007_hmmemitproject_external_hmm_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmmemitproject',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hmmemitproject',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_%(class)s_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hmmemitproject',
            index=models.Index(fields=['user', 'task_status', '-created_at'], name='hmmemit_hmm_user_id_810030_idx'),
        ),
        migrations.AddIndex(
            model_name='hmmemitproject',
            index=models.Index(fields=['user', 'expires_at'], name='hmmemit_hmm_user_id_ace7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='hmmemitproject',
            index=models.Index(fields=['visibility', 'expires_at'], name='hmmemit_hmm_visibil_2f811f_idx'),
        ),
    ]
