# Generated by Django 5.2.4 on 2025-12-28 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalHMMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('pfam', 'Pfam'), ('interpro', 'InterPro')], db_index=True, max_length=20)),
                ('external_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('hmm_file', models.FileField(upload_to='hmm_cache/%Y/%m/')),
                ('file_size', models.IntegerField(default=0)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('api_url', models.URLField(blank=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['source', 'external_id'], name='hmm_library_source_d5da82_idx'), models.Index(fields=['expires_at'], name='hmm_library_expires_575258_idx'), models.Index(fields=['last_used_at'], name='hmm_library_last_us_dc60f1_idx')],
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='HMMDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('pfam', 'Pfam'), ('interpro', 'InterPro')], max_length=20)),
                ('external_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('hmm_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='hmm_library.externalhmmmodel')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
