# Generated by Django 5.2.4 on 2026-01-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmm_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalhmmmodel',
            name='has_pfam_model',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='externalhmmmodel',
            name='pfam_members',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
