# Generated by Django 5.2.4 on 2026-01-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmm_library', '0002_externalhmmmodel_has_pfam_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalhmmmodel',
            name='hmm_file',
            field=models.FileField(blank=True, null=True, upload_to='hmm_cache/%Y/%m/'),
        ),
    ]
