# Generated by Django 5.2.4 on 2026-01-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmm_library', '0003_alter_externalhmmmodel_hmm_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalhmmmodel',
            options={'ordering': ['-downloaded_at']},
        ),
        migrations.RemoveIndex(
            model_name='externalhmmmodel',
            name='hmm_library_last_us_dc60f1_idx',
        ),
        migrations.RemoveField(
            model_name='externalhmmmodel',
            name='last_used_at',
        ),
        migrations.RemoveField(
            model_name='externalhmmmodel',
            name='usage_count',
        ),
    ]
