# Generated by Django 5.2.4 on 2025-08-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmbuild', '0002_hmmbuildproject_result_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmmbuildproject',
            name='hmm_file',
            field=models.FileField(blank=True, null=True, upload_to='hmmbuild/'),
        ),
        migrations.AlterField(
            model_name='hmmbuildproject',
            name='msa_file',
            field=models.FileField(upload_to='hmmbuild/'),
        ),
        migrations.AlterField(
            model_name='hmmbuildproject',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
