# Generated by Django 5.2.4 on 2025-12-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmbuild', '0003_alter_hmmbuildproject_hmm_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmmbuildproject',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hmmbuildproject',
            name='task_status',
            field=models.CharField(blank=True, default='PENDING', max_length=50, null=True),
        ),
    ]
