# Generated by Django 5.2.4 on 2025-12-26 20:55

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmbuild', '0006_hmmbuildproject_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hmmbuildproject',
            name='share_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='hmmbuildproject',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_hmmbuild_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hmmbuildproject',
            name='visibility',
            field=models.CharField(choices=[('private', 'Privatus'), ('link', 'Su nuoroda'), ('public', 'Viešas')], db_index=True, default='private', max_length=10),
        ),
    ]
