# Generated by Django 5.2.4 on 2026-01-14 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmbuild', '0007_hmmbuildproject_share_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmmbuildproject',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_%(class)s_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hmmbuildproject',
            index=models.Index(fields=['user', 'task_status', '-created_at'], name='hmmbuild_hm_user_id_c2221a_idx'),
        ),
        migrations.AddIndex(
            model_name='hmmbuildproject',
            index=models.Index(fields=['user', 'expires_at'], name='hmmbuild_hm_user_id_2becd0_idx'),
        ),
        migrations.AddIndex(
            model_name='hmmbuildproject',
            index=models.Index(fields=['visibility', 'expires_at'], name='hmmbuild_hm_visibil_68d4be_idx'),
        ),
    ]
