# Generated by Django 5.2.4 on 2026-05-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmmbuild', '0009_add_share_inputs_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmmbuildproject',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
